import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/navigationBar";
import { StrictMode } from "react";
import Providers from "./providers/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AuraDrive Resort - VoyageAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StrictMode>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Providers>
            <NavigationBar />
            {children}
          </Providers>
        </body>
      </html>
    </StrictMode>
  );
}
